### ISSUE TITLE
Testing private messages

### ISSUE THREAD

**Issue by ghostsquad** [mtsmfm/hubot-test-helper#13]
How do I test private messages? or posting a message to a specific room?

**Comment by mtsmfm** [comment]
@ghostsquad Thank you your feedback!
There is a exmaple as a test.
https://github.com/mtsmfm/hubot-test-helper/blob/master/test/private-message_test.coffee
I'll write it on README.

**Comment by ghostsquad** [comment]
Oh thank you! Looks good.
