### ISSUE TITLE
npm package is jS-incompatible

### ISSUE THREAD

**Issue by kengz** [mtsmfm/hubot-test-helper#21]
npm packages published in `JS` can be used by both `JS` and `coffeescript` users; whereas a `coffeescript` npm package cannot be used inside a `.js` file. Despite the fact that most hubot users are `coffeescript`-based, it's good to have a broader compatibility.

I'll include a pull request to address the issue soon. Thanks.

**Comment by mtsmfm** [comment]
Close via #22
