### ISSUE TITLE
allow for userId

### ISSUE THREAD

**Issue by kengz** [mtsmfm/hubot-test-helper#26]
Most adapters have distinct userName and userId. The constructor [here](https://github.com/mtsmfm/hubot-test-helper/blob/master/src/index.coffee#L39) is the default `Hubot.user, which sets the id to the username.

Can we allow for a quick enhancement to set both the username and id? So the argument would be like
`receive: (userNameId, message) ->`
where `userNameId` can be a string (back to the original use case), or if it's an array then it shall contain `[name, id]`, which will be set accordingly in the `user` object.

**Comment by mtsmfm** [comment]
@kengz 

Sorry for very slow response :bow: :sweat_drops: 

How about `user.say('alice', '@hubot hi', id: 123)` ?

**Comment by mtsmfm** [comment]
I'm very happy if you tell me what you want to test :smile:

**Comment by kengz** [comment]
Hey yep adding a third optional id argument is good.

Hubot allows searching for user via `id` or `name`. This is [one test example](https://github.com/kengz/aiva/blob/master/test/scripts/test_todo.coffee#L26), where the bot can run function by searching a username, or searching by id as a fallback.

**Comment by alFReD-NSH** [comment]
It'd also be nice if we could add other stuff as well. For example the Slack adaptor has a `profile` property for the user. I can quickly add this if you guys are open to contributions :)

**Comment by mtsmfm** [comment]
@alFReD-NSH Sorry, I can't take a time to tuckle with this issue so please feel free to send PR!

**Comment by alFReD-NSH** [comment]
Hi guys, I just made a pull request that can do this. However according to the Hubot code, if you want a different id than user you should do this instead: `user.say(123, '@hubot hi', name: 'alice')`.
