### ISSUE TITLE
how to mock a specific room/channel

### ISSUE THREAD

**Issue by tpowellmeto** [mtsmfm/hubot-test-helper#27]
Hi, in my functional code I am using the messageRoom function controlled by a cronjob to post a salutation message each morning. 
```
robot.messageRoom('general', 'hello general room');
```
How can I mock the 'general' room to provide a test for this functionality?

**Comment by pchaigno** [comment]
@tpowellmeto I think you'll need to use [the `name` option](https://github.com/mtsmfm/hubot-test-helper/blob/master/src/index.coffee#L89) when you call `createRoom`. I've never used it before though.

**Comment by tpowellmeto** [comment]
@pchaigno Thank you that worked!
```
room = helper.createRoom({name:'roomName'});
```
