### ISSUE TITLE
Cannot find module `hubot`

### ISSUE THREAD

**Issue by hpurmann** [mtsmfm/hubot-test-helper#33]
Hey!

I tried using your test helper on an ES6 codebase. I tried to write an integration test with it but just requiring the module fails:

```javascript
const Helper = require('hubot-test-helper')
```

I get `cannot find module 'hubot'`. I don't know what's happening here. I even have `hubot` in my own `package.json`. Do you have any clue how to resolve this?

**Comment by mtsmfm** [comment]
Could you show me whole example?

**Comment by hpurmann** [comment]
I think I found the issue. Hubot is published as coffee script, not as javascript. Means I would need to transpile the node module before requiring it.

**Comment by levichen** [comment]
Hi @hpurmann I have same issue. Could you please tell me how to fix it?

**Comment by hpurmann** [comment]
I'm sorry, didn't investigate further. There is an issue which [discusses the transition to es6](https://github.com/github/hubot/issues/1138).

**Comment by kurtismgit** [comment]
I was hitting the same issue.  For me the solution was to create a mocha.opts file in my test folder with this content:

--require coffee-script/register
--compilers coffee:coffee-script

**Comment by hpurmann** [comment]
Thanks @kurtismgit for this workaround.

As this problem is not due to `hubot-test-helper` but due to the fact that `hubot` is not publishing transpiled JS to NPM, I'm closing this issue.
