### ISSUE TITLE
please add support testing scripts that depends on other middle-ware only scripts 

### ISSUE THREAD

**Issue by mosheBelostotsky** [mtsmfm/hubot-test-helper#34]
Please add support for such external scripts that should be loaded before the tested script
and the tested script rely on.
Example script: https://github.com/HelloFax/hubot-auth-middleware

**Comment by soninob** [comment]
+1

**Comment by JonathanRosado** [comment]
+1

**Comment by mtsmfm** [comment]
@mosheBelostotsky 

Could you tell me the ideal test code :question: 
It won't work at this time but I want to know how do you want to write test :pray:

**Comment by mosheBelostotsky** [comment]
@mtsmfm Thanks for your quick response!

Here is an example of proposed test code, Assuming library hubot-x must be loaded before hello-world.js
```coffee
# ...
helper = new Helper(['../hubot-x/src', '../scripts/hello-world.js'])
# ....
describe 'external middleware tests', ->
  beforeEach ->
    @room = helper.createRoom()
```

I will send *PR* now
