### ISSUE TITLE
Room destroy throws error when httpd is false

### ISSUE THREAD

**Issue by timkinnane** [mtsmfm/hubot-test-helper#39]
e.g. (coffeescript)

```
  beforeEach ->
    @room = helper.createRoom httpd: false

  afterEach ->
    @room.destroy()
```

Throws `TypeError: Cannot read property 'close' of undefined`.

I think because `.destroy` is just a proxy for `@robot.server.close()` which maybe shouldn't be run if there was no httpd server created? Just guessing, sorry I didn't have time to contribute more.

**Comment by mtsmfm** [comment]
Thank you for your reporting!
I'll investigate about that but I din't have time too so it may take a while 😓

**Comment by pchaigno** [comment]
# should fix it. @timkinnane Could you check on your side?

**Comment by timkinnane** [comment]
Thanks @pchaigno, your changes look good, but can you give me a hint how to test it. I tried npm installing the repo from github, but it seems that it needs to be compiled by the npm publish process on a proper version release to work via npm. Are you just cloning and running the prepublish script locally then requiring the path?

**Comment by pchaigno** [comment]
You can temporarily replace the version for `hubot-test-helper` in your `package.json` file with my repository and branch:
`"hubot-test-helper": "pchaigno/hubot-test-helper#fix-room-destroy-httpd",`

**Comment by timkinnane** [comment]
I tried doing that with my own fork and got an error from npm install, because `No version provided in package.json`, so I added the version to my fork's package.json, but then found that the /src folder is in the `.npmignore` so it can't be used as a node module from the repo. I think it needs to be cloned and built locally, I was just trying to avoid the bother. :/
