### ISSUE TITLE
how do you run the tests?

### ISSUE THREAD

**Issue by andela-bnkengsa** [mtsmfm/hubot-test-helper#4]

**Comment by sukima** [comment]
Do you mean the tests for *this* repo?

This is what I did:

```console
$ git clone https://github.com/mtsmfm/hubot-test-helper.git
$ cd hubot-test-helper
$ npm install
$ npm test
```

**Comment by mtsmfm** [comment]
Thank you @sukima :star2: 

@andela-bnkengsa Please reopen and comment on this issue if you still have a problem :smile:
