### ISSUE TITLE
[Question] Testing adapter-specific send() code

### ISSUE THREAD

**Issue by stephenyeargin** [mtsmfm/hubot-test-helper#55]
I have a handful of Hubot packages that have a pattern similar to this:

```coffeescript

isSlack = robot.adapterName == 'slack'

// ...

if isSlack
  msg.send {
    attachments: [
      {
        text: 'a Slack-specific envelope',
        thumbnail: 'https://example.com/image.png'
        // ...
      }
    ]
  }
else
  msg.send 'regular IRC response'

```

The trouble is I cannot seem to figure out how to trick the test helper into thinking it has loaded an adapter named 'slack' (I'm only testing the output, so no other capabilities from the adapter are needed). As of right now, I can only write tests against the standard `msg.send()` response.

Has anyone worked with a similar case?

**Comment by jgarec** [comment]
Hi,

Some workarounds i've found : 

1. Create a script in test folder to be loaded before your real script :
```
new Helper(['my-custom-script.js', 'my-real-script-to-be-tested.js']);
```
which contains : 
```
module.exports = function(robot) {
    robot.adapterName = 'slack';
}
```

2. just set properties after calling createRoom ? 
`this.room.robot.adapterName = 'slack';`

Is it what you're looking for ?

**Comment by stephenyeargin** [comment]
@jgarec This worked great! I did try it with another package that has a slightly more complicated set up for testing and ran into some issues, but it worked fine on a more straightforward package. I do think it would be valuable if this could be overridden in a specific context rather than having to maintain a separate shim, but the workaround gets the job done.
